### ISSUE TITLE
uninitialized constant BatchLoader::Executor::Set (NameError)

### ISSUE THREAD

**Issue by schovi** [exAspArk/batch-loader#1]
Hi,

trying this awesome library and immediately bump into this error:

```
/Users/schovi/.rvm/gems/ruby-2.4.0@playground/gems/batch-loader-1.0.0/lib/batch_loader/executor.rb:22:in `block in initialize': uninitialized constant BatchLoader::Executor::Set (NameError)
	from /Users/schovi/.rvm/gems/ruby-2.4.0@playground/gems/batch-loader-1.0.0/lib/batch_loader/executor_proxy.rb:46:in `items_to_load'
	from /Users/schovi/.rvm/gems/ruby-2.4.0@playground/gems/batch-loader-1.0.0/lib/batch_loader/executor_proxy.rb:16:in `add'
	from /Users/schovi/.rvm/gems/ruby-2.4.0@playground/gems/batch-loader-1.0.0/lib/batch_loader.rb:22:in `batch'
	from main.rb:4:in `block in <main>'
	from main.rb:3:in `times'
	from main.rb:3:in `each'
	from main.rb:3:in `map'
	from main.rb:3:in `<main>'
```

I tried to minimize code:

```
require "batch-loader"

3.times.map do |i|
  BatchLoader.for(i).batch do |somethings, loader|
    somethings.each do |val| loader.call(val, val) end
  end
end
```

Having
ruby 2.4.0
batch-loader 1.0.0

**Comment by exAspArk** [comment]
@schovi thank you so much for reporting the issue! 🙌 

Seems that some other development dependencies (like `rspec`, `graphql`, etc.) usually required `set`, so it didn't fail. Release the fix in the `1.0.1` version.
