### ISSUE TITLE
Incompatibility with graphql-ruby 2.0.18+

### ISSUE THREAD

**Issue by swrobel** [exAspArk/batch-loader#87]
It seems there was a [breaking change](https://github.com/rmosolgo/graphql-ruby/pull/4344) introduced in 2.0.18 that causes `use BatchLoader::GraphQL` to cause the following exception:

```
vendor/bundle/ruby/3.2.0/gems/graphql-2.0.19/lib/graphql/schema.rb:944:in `tracer': Can't add tracer after configuring a `trace_class`, use GraphQL::Tracing::LegacyTrace to merge legacy tracers into a trace class instead.
  raise ArgumentError, "Can't add tracer after configuring a `trace_class`, use GraphQL::Tracing::LegacyTrace to merge legacy tracers into a trace class instead."
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ (ArgumentError)
from vendor/bundle/ruby/3.2.0/gems/batch-loader-2.0.1/lib/batch_loader/graphql.rb:10:in `use'
from vendor/bundle/ruby/3.2.0/gems/graphql-2.0.19/lib/graphql/schema.rb:243:in `use'
```

**Comment by chriswright47** [comment]
I'm also seeing this issue in my application. I am working around it for the moment by locking the `graphql` gem version to `2.0.17`:
```
gem "graphql", "~> 2.0", "<= 2.0.17"
```

**Comment by pravi** [comment]
There are other braking changes too, with graphql 2.2.8, I see
```

An error occurred while loading /<<PKGBUILDDIR>>/spec/batch_loader/middleware_spec.rb.
Failure/Error: use GraphQL::Execution::Interpreter

NoMethodError:
  undefined method `use' for GraphQL::Execution::Interpreter:Class

            plugin.use(self)
                  ^^^^
# /usr/share/rubygems-integration/all/gems/graphql-2.2.5/lib/graphql/schema.rb:317:in `use'
# /<<PKGBUILDDIR>>/spec/fixtures/graphql_schema.rb:37:in `<class:GraphqlSchemaWithInterpreter>'
# /<<PKGBUILDDIR>>/spec/fixtures/graphql_schema.rb:36:in `<top (required)>'
# /<<PKGBUILDDIR>>/spec/spec_helper.rb:12:in `require_relative'
# /<<PKGBUILDDIR>>/spec/spec_helper.rb:12:in `<top (required)>'
# /<<PKGBUILDDIR>>/spec/batch_loader/middleware_spec.rb:1:in `<top (required)>'

An error occurred while loading /<<PKGBUILDDIR>>/spec/batch_loader_spec.rb.
Failure/Error: query QueryType

GraphQL::Error:
  Second definition of `query(...)` (QueryType) is invalid, already configured with QueryType
# /usr/share/rubygems-integration/all/gems/graphql-2.2.5/lib/graphql/schema.rb:418:in `query'
# /<<PKGBUILDDIR>>/spec/fixtures/graphql_schema.rb:31:in `<class:GraphqlSchema>'
# /<<PKGBUILDDIR>>/spec/fixtures/graphql_schema.rb:30:in `<top (required)>'
# /<<PKGBUILDDIR>>/spec/spec_helper.rb:12:in `require_relative'
# /<<PKGBUILDDIR>>/spec/spec_helper.rb:12:in `<top (required)>'
# /<<PKGBUILDDIR>>/spec/batch_loader_spec.rb:1:in `<top (required)>'

An error occurred while loading /<<PKGBUILDDIR>>/spec/graphql_spec.rb.
Failure/Error: query QueryType

GraphQL::Error:
  Second definition of `query(...)` (QueryType) is invalid, already configured with QueryType
# /usr/share/rubygems-integration/all/gems/graphql-2.2.5/lib/graphql/schema.rb:418:in `query'
# /<<PKGBUILDDIR>>/spec/fixtures/graphql_schema.rb:31:in `<class:GraphqlSchema>'
# /<<PKGBUILDDIR>>/spec/fixtures/graphql_schema.rb:30:in `<top (required)>'
# /<<PKGBUILDDIR>>/spec/spec_helper.rb:12:in `require_relative'
# /<<PKGBUILDDIR>>/spec/spec_helper.rb:12:in `<top (required)>'
# /<<PKGBUILDDIR>>/spec/graphql_spec.rb:1:in `<top (required)>'
No examples found.


```

**Comment by exAspArk** [comment]
Sorry, I don't have the bandwidth to address this issue right now. Please feel free to submit a pull request, and I'd be happy to review and merge it 🙏

**Comment by boutil** [comment]
It seems that applying:
```
--- a/spec/fixtures/graphql_schema.rb
+++ b/spec/fixtures/graphql_schema.rb
@@ -34,8 +34,6 @@
 
 if defined?(GraphQL::Execution::Interpreter)
   class GraphqlSchemaWithInterpreter < GraphQL::Schema
-    use GraphQL::Execution::Interpreter
-    use GraphQL::Analysis::AST
     query QueryType
     use BatchLoader::GraphQL
   end
```
is enough to make the test suite pass with ruby3.1
